assessment/urls.py
from django.urls import include, path
from django.contrib import admin

urlpatterns = [
    path('admin/', admin.site.urls),
    path('maturity/', include('maturity.urls'))
]

maturity/urls.py
from django.urls import path

from . import views

app_name = 'maturity'
urlpatterns = [path('', views.MainPageView.as_view(), name='index'),
               path('assessments/', views.AssessmentListView.as_view(), name='assessments'),
               path('assessments/<int:pk>', views.AnswerListView.as_view(), name='answers'),
               path('assessments/answer/<int:pk>', views.AnswerView.as_view(), name='answer'),
               path('assessments/set_answer/<int:assessment_id>', views.set_answer, name='set_answer'),
               path('assessments/set/', views.set_new_assessment_data, name='set_new_assessment_data'),
               path('assessments/results/<int:pk>', views.ResultsView.as_view(), name='results')]

maturity/models.py
from django.db import models
from django.db.models import Avg
from django.utils import timezone

# Create your models here.

class Dimension(models.Model):
    dimension_name = models.CharField(max_length=64)
    dimension_description = models.CharField(max_length=500)

    def __str__(self):
        return self.dimension_name
        # + ' (' + str(self.pk) + ')'

class Criteria(models.Model):
    dimension = models.ForeignKey(Dimension, on_delete=models.CASCADE)
    criteria_name = models.CharField(max_length=64)
    criteria_description = models.CharField(max_length=500)

    def __str__(self):
        return self.criteria_name


class Assessment(models.Model):
    assessment_date = models.DateTimeField()
    user_name = models.CharField(max_length=120)
    user_email = models.CharField(max_length=120)
    current_assessment_item = models.IntegerField(default=-1)

    def __str__(self):
        return 'Assessment of ' + self.user_email + ' (' + str(self.pk) + ')'

    def create_answers(self):
        dimension_list = Dimension.objects.all()
        for dimension in dimension_list:
            DimensionResult.objects.create(assessment=self, dimension=dimension, value=-1)
        criteria_list = Criteria.objects.all()
        for crit in criteria_list:
            AssessmentAnswer.objects.create(assessment=self, criteria=crit, value=-1)

    def set_dimension_results(self):
        dimension_result_list = list(self.dimensionresult_set.all())
        for dimension_result in dimension_result_list:
            result = self.get_dimension_result(dimension_result.dimension)
            dimension_result.value = result
            dimension_result.save()
        return self.dimensionresult_set.all()

    def create_dimension_results(self):
        dimension_list = list(Dimension.objects.all())
        for dimension in dimension_list:
            result = self.get_dimension_result(dimension)
            dimension_result = DimensionResult.objects.create(assessment=self, dimension=dimension, value=result)
            dimension_result.save()
        return self.dimensionresult_set.all()

    def get_current_assessment_item(self):
        answer_list = list(self.assessmentanswer_set.all())
        if self.current_assessment_item < len(answer_list):
            answer = answer_list[self.current_assessment_item]
        else:
            self.set_dimension_results()
            answer = None
        return answer

    def get_progress_string(self):
        answer_list = list(self.assessmentanswer_set.all())
        str_return = str(self.current_assessment_item+1) + '/' + str(len(answer_list))
        return str_return


    def get_dimension_result(self, dimension):
        answers = self.assessmentanswer_set.filter(criteria__dimension__dimension_name=dimension.dimension_name)
        result = answers.aggregate(Avg('value'))
        return result.get('value__avg')

    def get_dimension_list(self):
        return Dimension.objects.all()

    def set_current_answer(self, value):
        answer = self.get_current_assessment_item()
        answer.set_value(value)
        answer.save()
        self.current_assessment_item = self.current_assessment_item + 1

    def field_list_view(self):
        return [self.user_email, self.user_name, str(self.assessment_date)]

    @staticmethod
    def createAssessment(name, email):
        ass = Assessment.objects.create(user_name=name, user_email=email, assessment_date=timezone.now(), current_assessment_item=0)
        ass.create_answers()
        return ass

class AssessmentAnswer(models.Model):
    assessment = models.ForeignKey(Assessment, on_delete=models.CASCADE)
    criteria = models.ForeignKey(Criteria, on_delete=models.CASCADE)
    value = models.IntegerField()

    def __str__(self):
        return self.get_dimension_name() + ' | ' + self.get_criteria_name() + ' | ' + str(self.value)

    def set_value(self, new_value):
        self.value = new_value

    def get_dimension_name(self):
        return str(self.criteria.dimension)

    def get_criteria_name(self):
        return str(self.criteria)

    def get_criteria_description(self):
        return self.criteria.criteria_description

    def get_assessment_name(self):
        return str(self.assessment)

class DimensionResult(models.Model):
    assessment = models.ForeignKey(Assessment, on_delete=models.CASCADE)
    dimension = models.ForeignKey(Dimension, on_delete=models.CASCADE)
    value = models.FloatField()

    def __str__(self):
        return str(self.dimension) + ' | ' + str(self.value)

maturity/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.views import generic
from django.views.generic.edit import FormView
from .models import Assessment, AssessmentAnswer, Dimension, Criteria
from django import forms
from django.urls import reverse

class MainPageView(generic.ListView):
    template_name = 'html5boilerplate/index.html'
    def get_queryset(self):
        return Dimension.objects.all()

class AssessmentListView(generic.ListView):
    template_name = 'maturity/assessment_list.html'
    def get_queryset(self):
        return Assessment.objects.all()

class AnswerView(generic.DetailView):
    model = Assessment
    template_name = 'html5boilerplate/criteriaanswer.html'

class AnswerListView(generic.DetailView):
    model = Assessment
    template_name = 'maturity/answer_list.html'

class ResultsView(generic.DetailView):
    model = Assessment
    template_name = 'html5boilerplate/results.html'

def set_new_assessment_data(request):
    name = request.POST['name']
    email = request.POST['email']
    ass = Assessment.createAssessment(name, email)
    return HttpResponseRedirect(reverse('maturity:answer', args=(ass.id,)))

def set_answer(request, assessment_id):
    ass = Assessment.objects.get(pk=assessment_id)
    answer = int(request.POST['value'])
    ass.set_current_answer(answer)
    ass.save()
    answer = ass.get_current_assessment_item() # gets next item
    if answer == None:
        return HttpResponseRedirect(reverse('maturity:results', args=(ass.id,)))
    else:
        return HttpResponseRedirect(reverse('maturity:answer', args=(ass.id,)))

maturity/templates/html5boilerplate/answer.html
{% load static %}

<!doctype html>
<html class="no-js" lang="">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="x-ua-compatible" content="ie=edge">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <link rel="manifest" href="site.webmanifest">
        <link rel="apple-touch-icon" href="icon.png">
        <!-- Place favicon.ico in the root directory -->

        <link rel="stylesheet" href="css/normalize.css">
        <link rel="stylesheet" href="css/main.css">

        <!-- CSS -->
        <link rel='stylesheet' href='http://fonts.googleapis.com/css?family=PT+Sans:400,700'>
        <link rel="stylesheet" href="{% static 'assets/bootstrap/css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'assets/prettyPhoto/css/prettyPhoto.css' %}">
        <link rel="stylesheet" href="{% static 'assets/font-awesome/css/font-awesome.css' %}">
        <link rel="stylesheet" href="{% static 'assets/css/social-icons.css' %}">
        <link rel="stylesheet" href="{% static 'assets/css/ebook-style.css' %}">

    </head>
    <body>
        <!--[if lte IE 9]>
            <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="https://browsehappy.com/">upgrade your browser</a> to improve your experience and security.</p>
        <![endif]-->

        <!-- Header -->
        <div class="container">
            <div class="header row">
                <div class="logo span4">
                    <h2><a href="">Avaliação Digital</a></h2>
                </div>
                <div class="tel-skype span8">
                    <p><a href="https://overdub.tech">overdub.tech</a><span class="pipe">|</span> <i class="icon-user"></i> <a href="mailto:contato@overdub.tech">contato@overdub.tech</a> </p>
                </div>
            </div>
        </div>

        <div class="container">
            <div class="row">
                <div class="question-area">
                    <div class="question">
                        <h3>Dimensão: {{ assessment.get_current_assessment_item.get_dimension_name }}</h3>
                        <h5>Critério: {{ assessment.get_current_assessment_item.get_criteria_name }}</h5>
                        <p>{{ assessment.get_current_assessment_item.get_criteria_description }}</p>
                        <form action="{% url 'maturity:set_answer' assessment.id %}" method="post" class="subscribe">{% csrf_token %}
                            <input type="radio" name="value" value="1"> 1 |
                            <input type="radio" name="value" value="2"> 2 |
                            <input type="radio" name="value" value="3"> 3 |
                            <input type="radio" name="value" value="4"> 4 |
                            <input type="radio" name="value" value="5"> 5 <br>
                            <p><button type="submit">Enviar</button></p>
                        </form>
                    </div>
                </div>
            </div>
        </div>


        <footer>
            <div class="container">

                <div class="row">
                    <div class="span12 copyright">
                        <p>Avaliação Digital: todos os diretos reservados à overdub.tech</p>
                    </div>
                </div> <!-- end row -->

            </div>
        </footer>


        <script src="js/vendor/modernizr-3.5.0.min.js"></script>
        <script src="https://code.jquery.com/jquery-3.2.1.min.js" integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4=" crossorigin="anonymous"></script>
        <script>window.jQuery || document.write('<script src="js/vendor/jquery-3.2.1.min.js"><\/script>')</script>
        <script src="js/plugins.js"></script>
        <script src="js/main.js"></script>


    </body>
</html>

maturity/templates/html5boilerplate/criteriaanswer.html
{% load static %}

<!doctype html>
<html class="no-js" lang="">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="x-ua-compatible" content="ie=edge">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <link rel="manifest" href="site.webmanifest">
        <link rel="apple-touch-icon" href="icon.png">
        <!-- Place favicon.ico in the root directory -->

        <link rel='stylesheet' href='http://fonts.googleapis.com/css?family=PT+Sans:400,700'>
        <link rel="stylesheet" href="{% static 'assets/css/normalize.css' %}">
        <link rel="stylesheet" href="{% static 'assets/css/mycss.css' %}">
        <link rel="stylesheet" href="{% static 'assets/font-awesome/css/font-awesome.css' %}">
    </head>
    <body>
        <!--[if lte IE 9]>
            <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="https://browsehappy.com/">upgrade your browser</a> to improve your experience and security.</p>
        <![endif]-->


        <div class="mycontainer">
            <div class="question-header">
                <div class="logo-overdub">
                    <img src="{% static 'assets/img/overdub.png' %}" width="100" height="22">
                </div>
                <div class="map-title">
                    <b> | mapa digital</b>
                </div>
            </div>
            <div class="progress-bar-area">
                <div class="progress-bar">
                    {{ assessment.get_progress_string }}
                </div>
            </div>
            <div class="text-area">
                <div class="dimension-text">
                    <b>{{ assessment.get_current_assessment_item.get_dimension_name }}</b>
                </div>
                <div class="criteria-text">
                    {{ assessment.get_current_assessment_item.get_criteria_name }}
                </div>
                <div class="criteria-description">
                    {{ assessment.get_current_assessment_item.get_criteria_description }}
                </div>
            </div>
            <form action="{% url 'maturity:set_answer' assessment.id %}" method="post" class="subscribe">{% csrf_token %}
                <div class="vote-area">
                    <div class="button-vote"><input type="radio" name="value" value="1">1</div>
                    <div class="button-vote"><input type="radio" name="value" value="2">2</div>
                    <div class="button-vote"><input type="radio" name="value" value="3">3</div>
                    <div class="button-vote"><input type="radio" name="value" value="4">4</div>
                    <div class="button-vote"><input type="radio" name="value" value="5">5</div>
                </div>
                <div class="navigate-area">
                    <div class="button-navigate"><button type="submit">< anterior</button></div>
                    <div class="button-navigate"><button type="submit">próximo ></button></div>
                </div>
            </form>
        </div>


        <script src="js/vendor/modernizr-3.5.0.min.js"></script>
        <script src="https://code.jquery.com/jquery-3.2.1.min.js" integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4=" crossorigin="anonymous"></script>
        <script>window.jQuery || document.write('<script src="js/vendor/jquery-3.2.1.min.js"><\/script>')</script>
        <script src="js/plugins.js"></script>
        <script src="js/main.js"></script>


    </body>
</html>

maturity/templates/html5boilerplate/index.html
{% load static %}

<!doctype html>
<html class="no-js" lang="">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="x-ua-compatible" content="ie=edge">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <link rel="manifest" href="site.webmanifest">
        <link rel="apple-touch-icon" href="icon.png">
        <!-- Place favicon.ico in the root directory -->

        <link rel="stylesheet" href="css/normalize.css">
        <link rel="stylesheet" href="css/main.css">

        <!-- CSS -->
        <link rel='stylesheet' href='http://fonts.googleapis.com/css?family=PT+Sans:400,700'>
        <link rel="stylesheet" href="{% static 'assets/bootstrap/css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'assets/prettyPhoto/css/prettyPhoto.css' %}">
        <link rel="stylesheet" href="{% static 'assets/font-awesome/css/font-awesome.css' %}">
        <link rel="stylesheet" href="{% static 'assets/css/social-icons.css' %}">
        <link rel="stylesheet" href="{% static 'assets/css/ebook-style.css' %}">

    </head>
    <body>
        <!--[if lte IE 9]>
            <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="https://browsehappy.com/">upgrade your browser</a> to improve your experience and security.</p>
        <![endif]-->

        <!-- Header -->
        <div class="container">
            <div class="header row">
                <div class="logo span4">
                    <h2><a href="">Avaliação Digital</a></h2>
                </div>
                <div class="tel-skype span8">
                    <p><a href="https://overdub.tech">overdub.tech</a><span class="pipe">|</span> <i class="icon-user"></i> <a href="mailto:contato@overdub.tech">contato@overdub.tech</a> </p>
                </div>
            </div>
        </div>

        <!-- Product Showcase -->
        <div class="product-showcase">
            <div class="product-showcase-pattern">
                <div class="container">
                    <div class="row">
                        <div class="span12 product-background">
                            <div class="row">
                                <div class="span5 product-image">
                                    <img src="{% static 'assets/img/ebook.png' %}" alt="">
                                </div>
                                <div class="span7 product-title">
                                    <h1>Avaliação Digital</h1>
                                    <div class="product-description">
                                        <p><strong>Você está preparado para a transformação digital?</strong></p>
                                        <p>Avalie gratuitamente o grau de maturidade digital da sua empresa.</p>
                                        <p>Receba um relatório com o resultado de sua avaliação, diagnóstico e recomendações inciais.</p>
                                        <form action="{% url 'maturity:set_new_assessment_data' %}" method="post" class="subscribe">{% csrf_token %}
                                            <input type="text" name="name" class="text" placeholder="Digite seu nome">
                                            <input type="text" name="email" class="email" placeholder="Digite seu email">
                                            <button type="submit">iniciar</button>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="container">
            <!-- Os tres pilares da avaliação digital-->
            <div class="row">
                <div class="span12">
                    <div class="features_2">
                        <h3>Pilares da Avaliação Digital</h3>
                        <div class="row">
                            <div class="span4 single-feature features-left-span">
                                <div class="feature-icon">
                                    <i class="icon-fire"></i>
                                </div>
                                <div class="feature-text">
                                    <h4>Cultura Digital</h4>
                                    <p>A cultura digital representa como sua empresa se organiza, qual a estratégia e
                                        a postura da liderança em relação à transformação digital e quais os valores e
                                        comportamentos de sua empresa que podem contribuir para a jornada digital.</p>
                                </div>
                            </div>
                            <div class="span4 single-feature">
                                <div class="feature-icon">
                                    <i class="icon-cloud"></i>
                                </div>
                                <div class="feature-text">
                                    <h4>Ativos Digitais</h4>
                                    <p>Os ativos digitais são todas as soluções tecnológicas utilizadas pela sua
                                        organização com foco em geração de valor para o negócio.</p>
                                </div>
                            </div>
                            <div class="span4 single-feature">
                                <div class="feature-icon">
                                    <i class="icon-twitter"></i>
                                </div>
                                <div class="feature-text">
                                    <h4>Engajamento Social e Experiência do Cliente</h4>
                                    <p>Como sua empresa se comunica e gera engajamento com o cliente e com a comunidade,
                                        como a empresa trata a experiência e jornada do cliente.</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <!-- sobre a overdub-->
            <div class="row">
                <div class="span12">
                    <div class="about-us_2">
                        <h3>Sobre a Overdub</h3>
                        <h5>Catalisar a transformação das empresas: este é o propósito da Overdub</h5>
                        <p>A Overdub atua em iniciativas de inovação, estratégia de TI, transformação digital e
                            cultura ágil. Somos o parceiro ideal para a jornada de transformação das empresas que
                            buscam competitividade frente à concorrência digital.
                            <a href="https://overdub.tech">Saiba mais.</a></p>
                    </div>
                </div>
            </div>

        </div>

        <footer>
            <div class="container">

                <div class="row">
                    <div class="span4 contact-us">
                        <h3><a href="https://overdub.tech/sobre">Entre em contato conosco!</a></h3>
                    </div>
                </div>

                <div class="row">
                    <div class="span12">
                        <div class="social-links">
                            <a class="facebook" href="https://www.facebook.com/overdub.tech/"></a>
                            <a class="twitter" href="https://twitter.com/@overdubtech/"></a>
                            <a class="email" href="mailto:contato@overdub.tech"></a>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="span12 copyright">
                        <p>Avaliação Digital: todos os diretos reservados à overdub.tech</p>
                    </div>
                </div> <!-- end row -->

            </div>
        </footer>
    </body>
</html>

maturity/templates/html5boilerplate/results.html
{% load static %}

<!doctype html>
<html class="no-js" lang="">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="x-ua-compatible" content="ie=edge">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <link rel="manifest" href="site.webmanifest">
        <link rel="apple-touch-icon" href="icon.png">
        <!-- Place favicon.ico in the root directory -->

        <link rel="stylesheet" href="css/normalize.css">
        <link rel="stylesheet" href="css/main.css">

        <!-- CSS -->
        <link rel='stylesheet' href='http://fonts.googleapis.com/css?family=PT+Sans:400,700'>
        <link rel="stylesheet" href="{% static 'assets/bootstrap/css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'assets/prettyPhoto/css/prettyPhoto.css' %}">
        <link rel="stylesheet" href="{% static 'assets/font-awesome/css/font-awesome.css' %}">
        <link rel="stylesheet" href="{% static 'assets/css/social-icons.css' %}">
        <link rel="stylesheet" href="{% static 'assets/css/ebook-style.css' %}">

    </head>
    <body>
        <!--[if lte IE 9]>
            <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="https://browsehappy.com/">upgrade your browser</a> to improve your experience and security.</p>
        <![endif]-->

        <!-- Header -->
        <div class="container">
            <div class="header row">
                <div class="logo span4">
                    <h2><a href="">Avaliação Digital</a></h2>
                </div>
                <div class="tel-skype span8">
                    <p><a href="https://overdub.tech">overdub.tech</a><span class="pipe">|</span> <i class="icon-user"></i> <a href="mailto:contato@overdub.tech">contato@overdub.tech</a> </p>
                </div>
            </div>
        </div>

        <div class="container">
            <div class="row">
                <div class="span12">
                    {% for result in assessment.dimensionresult_set.all %}
                        <p>{{ result.dimension.dimension_name }} |
                           {{ result.value }}</p>
                    {% endfor %}
                </div>
            </div>
        </div>

        <div class="container">
            <div class="row">
                <div class="span12">
                    {% for answer in assessment.assessmentanswer_set.all %}
                        <p>{{ answer.criteria.dimension.dimension_name }} |
                           {{ answer.get_criteria_name }} |
                           {{ answer.value }}</p>
                    {% endfor %}
                </div>
            </div>
        </div>

        <footer>
            <div class="container">

                <div class="row">
                    <div class="span4 contact-us">
                        <h3><a href="https://overdub.tech/sobre">Entre em contato conosco!</a></h3>
                    </div>
                </div>

                <div class="row">
                    <div class="span12">
                        <div class="social-links">
                            <a class="facebook" href="https://www.facebook.com/overdub.tech/"></a>
                            <a class="twitter" href="https://twitter.com/@overdubtech/"></a>
                            <a class="email" href="mailto:contato@overdub.tech"></a>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="span12 copyright">
                        <p>Avaliação Digital: todos os diretos reservados à overdub.tech</p>
                    </div>
                </div> <!-- end row -->

            </div>
        </footer>


        <script src="js/vendor/modernizr-3.5.0.min.js"></script>
        <script src="https://code.jquery.com/jquery-3.2.1.min.js" integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4=" crossorigin="anonymous"></script>
        <script>window.jQuery || document.write('<script src="js/vendor/jquery-3.2.1.min.js"><\/script>')</script>
        <script src="js/plugins.js"></script>
        <script src="js/main.js"></script>


    </body>
</html>

maturity/templates/maturity/answer_list.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'maturity/style.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'maturity/components.css' %}" />

<table>
    <thead>
        <tr>Answer List</tr>
        <tr><td>Dimension</td><td>Criteria</td><td>Description</td><td>Value</td></tr>
    </thead>
    <tbody>
        {% for answer in assessment.assessmentanswer_set.all %}
        <tr>
            <td>{{ answer.criteria.dimension.dimension_name }}</td>
            <td>{{ answer.get_criteria_name }}</td>
            <td>{{ answer.criteria.criteria_description}}</td>
            <td>
                <div class="slidecontainer"><input type="range" min="1" max="5" value="1" class="slider" id="myRange"></div>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>

maturity/templates/maturity/assessment_list.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'maturity/style.css' %}" />

<table>
    <thead>
        <tr>Assessment List</tr>
        <tr><td>e-mail</td><td>Nome</td><td>Data</td></tr>
    </thead>
    <tbody>
        {% for assessment in assessment_list %}
        <tr>
            <td><a href="{% url 'maturity:answers' assessment.id %}">{{ assessment.user_email }}</a></td>
            <td>{{ assessment.user_name }}</td>
            <td>{{ assessment.assessment_date }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>

maturity/templates/maturity/index.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'maturity/style.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'maturity/components.css' %}" />

<p>x</p>
<div class="slidecontainer">
  <input type="range" min="1" max="100" value="50" class="slider" id="myRange">
</div>

maturity/templates/maturity/new_assessment.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'maturity/style.css' %}" />

<h1>New Assessment</h1>

<form action="{% url 'maturity:set_new_assessment_data' %}" method="post">{% csrf_token %}
{{ form.as_p }}
<input type="submit" value="Save" />
</form>